### ISSUE TITLE
FSharp Samples

### ISSUE THREAD

**Issue by tams89** [nessos/GpuLinq#3]
Would it be possible to have some pure FSharp samples?

P.S. This is very nice work indeed!

**Comment by palladin** [comment]
I'm not sure if we can port all the CSharp samples (for F# technical reasons) and I need to check the details with @krontogiannis. Of course it would be great if you can contribute some easy fsharp samples like the Csharp DotProduct.

**Comment by tams89** [comment]
Fair enough, I'll see if I can drum up some examples. The main issue I seem to be having is getting access to the .AsGpuQueryExpr() from F#, a direct port of the example given seems to be trickier than it should. Could it be that I'm missing something obvious?

**Comment by palladin** [comment]
Sorry for the inconvenience, but the F# support needs some upfront work. @krontogiannis Is it possible to call the CSharp API from the F# code directly? (Maybe we can pass F# lambdas as LINQ expression trees)

**Comment by tams89** [comment]
No problem.

I've created helpers in C# and then called it from F# which does work.

Can I pass custom types, it seems only value types can be sent converted to
GPU array at the moment?

**Comment by palladin** [comment]
Yes only GPUArray of primitives or structs, because we copy them directly to GPU memory and the idea is to minimize data transfer between host and device memory.

**Comment by krontogiannis** [comment]
I'm not so sure any non-trivial examples can be ported to F#. AFAIK the F# compiler is producing Linq Expression trees from F# Quotations, which may lead to some problems:

``` fsharp

open System
open System.Linq.Expressions

type Expression with
    static member OfFunc(expr : Expression<Func<'T,'U>>) = expr
    static member OfAction(expr : Expression<Action<'T>>) = expr
```

In nested Expressions it should produce an Expression.Quote, but it returns this:

``` fsharp
let e1 = Expression.OfFunc(fun x -> Expression.OfFunc(fun y -> x + y))


val e1 : Expression<Func<int,Expression<Func<int,int>>>> =
  x => Expression.OfFunc.Static(QuotationToLambdaExpression(SubstHelper(NewDelegate (Func`2, y, Call (None, op_Addition, [x, y])), new [] {x}, new [] {Convert(x)})))
```

and in case of actions/blocks the compiler fails:

``` fsharp
let e2 = Expression.OfAction(fun (x : int) -> ignore(x) ; ())


System.NotSupportedException: Could not convert the following F# Quotation to a LINQ Expression Tree
--------
Sequential (Call (None, Ignore, [x]), Value (<null>))
-------------

   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in C:\Users\kostas\AppData\Local\Temp\~vsE3CB.fsx:line 13
Stopped due to error
```

**Comment by tams89** [comment]
Ah that is a problem...oh well thanks for the response chaps!
